name: SIO221A-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy==1.16.4
  - matplotlib==3.1.0
  - xarray==0.12.1
  - nc-time-axis
  - holoviews
  - bokeh
  - hvplot
  - datashader
  - netcdf4==1.4.2
  
